name: Build and Deploy the Image

on:
    workflow_dispatch: # To have the ability to run the workflow manually
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-push-images:
        runs-on: ubuntu-latest
        container:
            image: catthehacker/ubuntu:act-latest
        env:
            DOCKER_ORG: nairol203
            DOCKER_LATEST: stable
            RUNNER_TOOL_CACHE: /toolcache
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker BuildX
              uses: docker/setup-buildx-action@v2
              with: # replace it with your local IP
                  config-inline: |
                      [registry."gitea.home.nairol.me"] 
                        http = true
                        insecure = false                      

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: gitea.home.nairol.me # replace it with your local IP
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Get Meta
              id: meta
              run: |
                  echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
                  echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT                  

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: |
                      linux/amd64
                      linux/arm64                      
                  push: true
                  tags: | # replace it with your local IP and tags
                      gitea.home.nairol.me/${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
                      gitea.home.nairol.me/${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ env.DOCKER_LATEST }}
                  # tags: ${{ steps.meta.outputs.tags }}
                  # labels: ${{ steps.meta.outputs.labels }}


